// <auto-generated />
namespace HotelManagement.Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2015_12_16_8_14_09 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2015_12_16_8_14_09));
        
        string IMigrationMetadata.Id
        {
            get { return "201512161310010_2015_12_16_8_14_09"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
